import type { Configuration, Skill } from '@/types'

function substituteParams(template: string, params: Record<string, string>): string {
  let result = template
  for (const [key, value] of Object.entries(params)) {
    result = result.replaceAll(`{{${key}}}`, value)
  }
  return result
}

function generateHeader(config: Configuration): string {
  const date = new Date().toISOString().split('T')[0]
  return `#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Generated by ServUp v2
# Configuration: "${config.name}"
# OS: ${config.os}
# Date: ${date}
# ============================================================

# --- Colors and logging ---
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

log_info()    { echo -e "\${BLUE}[INFO]\${NC} $1"; }
log_success() { echo -e "\${GREEN}[OK]\${NC} $1"; }
log_warn()    { echo -e "\${YELLOW}[WARN]\${NC} $1"; }
log_error()   { echo -e "\${RED}[ERROR]\${NC} $1"; }

# --- Root check ---
if [ "$(id -u)" -ne 0 ]; then
  log_error "This script must be run as root"
  exit 1
fi

# --- Start timer ---
SECONDS=0

log_info "Starting server setup: ${config.name}"
echo ""
`
}

function generateOsDetection(config: Configuration): string {
  if (config.os === 'debian') {
    return `# --- OS: Debian/Ubuntu ---
log_info "Updating package cache..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
echo ""
`
  }
  return `# --- OS: RHEL/CentOS ---
log_info "Updating package cache..."
yum makecache -q
echo ""
`
}

function generateFooter(config: Configuration, enabledCount: number): string {
  return `
# ============================================================
echo ""
log_success "Setup complete! (${config.name})"
log_info "${enabledCount} skill(s) applied in \${SECONDS}s"
`
}

export function generateScript(config: Configuration, skills: Skill[]): string {
  const skillMap = new Map(skills.map((s) => [s.id, s]))

  const enabledEntries = config.entries.filter((e) => e.enabled)

  const parts: string[] = []

  parts.push(generateHeader(config))
  parts.push(generateOsDetection(config))

  for (const entry of enabledEntries) {
    const skill = skillMap.get(entry.skillId)
    if (!skill) continue

    const script = skill.scripts[config.os]
    if (!script) continue

    const rendered = substituteParams(script, entry.params)

    // Build a label for this entry
    let label = skill.name
    // For repeatable skills, show a distinguishing param
    if (skill.repeatable && skill.params.length > 0) {
      const firstParam = skill.params[0]
      const val = entry.params[firstParam.id]
      if (val) label += `: ${val}`
    }

    parts.push(`# --- ${label} ---`)
    parts.push(rendered.trim())
    parts.push('echo ""\n')
  }

  parts.push(generateFooter(config, enabledEntries.length))

  return parts.join('\n')
}
